language: node_js
node_js:
  - "6"
env:
  NODE_ENV: PRD
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "test.nic.eco"
    skip_cleanup: true
    region: "us-west-2"
    local_dir: public
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "nic.eco"
    skip_cleanup: true
    region: "us-west-2"
    local_dir: public
    on:
      branch: production