language: node_js
node_js:
  - "10"
env:
  NODE_ENV: TST
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "test.go.eco"
    skip_cleanup: true
    region: "us-west-2"
    local_dir: public
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "www.go.eco"
    skip_cleanup: true
    region: "us-west-2"
    local_dir: public
    on:
      branch: production
