version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
workflows:
 version: 2
 test:
   jobs:
     - build:
        context: TEST
        bucket: 's3://test.go.eco/'
        bucket-de: 's3://de.test.go.eco/'
        filters:
          branches:
            only: master
 production:
   jobs:
     - build:
        context: PROD
        bucket: 's3://www.go.eco/'
        bucket-de: 's3://de.go.eco/'
        filters:
          branches:
            only: production
jobs:
  build:
    parameters:
      bucket:
        type: string
      bucket-de:
        type: string
    docker:
    # Image tags available here: https://circleci.com/docs/2.0/docker-image-tags.json
    - image: $NODE_IMAGE
    steps:
    - checkout

    # Build
    - run: sudo apt-get install nasm
    - run: npm install
    # - run: node ./imagemin.mjs
    - run: npm run build
    - run: SITE_LANG=de npm run build

    # Deployment
    - aws-s3/sync:
        from: public
        to: << parameters.bucket >>

    - aws-s3/sync:
        from: public-de
        to: << parameters.bucket-de >>
